Avoid to encode the cover letter
stefanha/git-publish pull request #93
Opened 2020-08-28 10:33 UTC by stefano-garzarella

git-send-email seems to be not happy with a cover letter already
encoded. In fact, git-format-patch generates it without encoding.

This problem occurs especially if 'sendemail.transferEncoding' is
not set to auto.

To avoid issues, instead of using the 'email' module, which encodes the
final result, we simply replace the text in the cover letter file
generated by git-format-patch.

Fixes: #88
Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>

2020-08-28 13:50 UTC, stefanha requested changes
This commit causes a test failure. It seems long Subject: lines break again:

$ testing/run_tests.sh
Running test case 0005-subject-line-wrap: FAILED
--- Last 10 lines of test output: ---
git send-email not run using --dry-run
--- /tmp/tmp.mDeqUUEBtQ/0005-subject-line-wrap/expected	2020-08-28 14:48:47.860188109 +0100
+++ /tmp/tmp.mDeqUUEBtQ/0005-subject-line-wrap/found	2020-08-28 14:48:47.861188121 +0100
@@ -1,2 +1,2 @@
-Subject: [a very long long long long long long long long long test 0/1] This
- is the message
+Subject: [a very long long long long long long long long long test 0/1] ***
+ SUBJECT HERE ***
TEST FAILURE: Assertion failed: diff -u /tmp/tmp.mDeqUUEBtQ/0005-subject-line-wrap/expected /tmp/tmp.mDeqUUEBtQ/0005-subject-line-wrap/found

2020-08-28 14:04 UTC, stefano-garzarella commented
> This commit causes a test failure. It seems long Subject: lines break again:

:-( I forgot to run tests...

Now I see what `subject = msg['Subject'].replace('\n', '')` was for.

I'll try to fix this issue.

2020-08-28 15:50 UTC, stefano-garzarella commented
@stefanha I pushed a simpler solution replacing `set_content()`, which encodes the final result, with `set_payload()`.
The tests seem okay and even sending the cover letter that was giving me problems seems okay.

2020-08-29 13:12 UTC, merged

2020-08-29 13:13 UTC, stefanha commented
I have no idea whether the fix is "correct" because the email package is underdocumented. Mixing get_content() and set_payload() seems risky but the test still pass so let's give it a try. If an issue is found later we can revert this patch again.

2020-08-30 08:40 UTC, stefano-garzarella commented
Yeah, I just tried it, but was not so clear the difference until I tried it.

Maybe we can use `get_payload()` to not mix. I tried and it seems to work.

2020-08-30 09:12 UTC, stefanha commented
I'll run git-publish on my system with your current patch applied. If I don't notice any issues over the next few weeks I'll tag a new release.

If something goes wrong with message encoding I'll let you know and we can try to figure it out.